# Generated by Django 5.1 on 2024-10-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_savedproperties'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproperties',
            name='listing_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent'), ('lease', 'Lease')], default='buy', max_length=10),
        ),
    ]
