# Generated by Django 5.1 on 2024-10-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_savedproperties_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='listing_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent'), ('lease', 'Lease')], default='buy', max_length=10),
        ),
    ]
