# Generated by Django 5.1 on 2024-10-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_callrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='docusigntemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
