# Generated by Django 5.1 on 2024-10-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_docusigntemplate_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signed_contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
