# Generated by Django 5.1 on 2024-10-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_contract_signed_contract_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='is_signed_by_buyer',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='is_signed_by_owner',
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('sent_for_signing', 'Sent for Signing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
    ]
